### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by brencecoghill** [Genyus/cf7-agilecrm#2]
I had a go at installing this, but get the error:

**Plugin could not be activated because it triggered a fatal error.**

Parse error: syntax error, **unexpected '['** in /home/monstrous/public_html/calandra/wp-content/plugins/cf7-agilecrm-master/contact-form-7-agile.php on line 497

**Comment by Genyus** [comment]
Resolved by afd565c3b2b18aa7f7cdc5b1953ab3ec4599de63
