### ISSUE TITLE
Add a deal and/or ticket

### ISSUE THREAD

**Issue by RuBiCK** [Genyus/cf7-agilecrm#4]
The plugin is great but it would be gorgeous if it could create a deal associated to the contact.
Is it planned to create a new deal with other fields of the same form?

**Comment by Genyus** [comment]
This isn't a feature I had previously considered. It seems to me that while some deal fields could be easily automated (e.g. source, related to, tags, description, milestone) a number would usually be populated by the owner (e.g. name, value, close date, probability, etc).

The concerns that come to mind are how to enable useful deal-specific functionality without adding unnecessary complexity. If a user still has to jump into Agile to edit a number of fields for a newly-generated deal, then I'm not convinced it would be worth the effort of implementing.

However, if you can describe how you can envisage it working for your use case, I'll certainly give it some thought.

**Comment by RuBiCK** [comment]
In my case, we have different forms for different audience. 
- Contact form that create a helpdesk ticket. It can be made mapping text area field to agile crm ticket field
- Contact form for business. That we want to create a deal for each new entry. 

In order to keep it simple, it should be enough only relate the deal with the contact (a new one) and mapping a text field with notes or description of the deal. Only with that it will be great.

It will be fantastic to open Agile CRM and see deals coming from my wordpress site :)

What do you think about with this simple implementation?

**Comment by Genyus** [comment]
I have taken a look at this, but it does feel like it would take a good deal of effort for what is a fairly narrow use-case. Ultimately, given the other demands on my time, it's not a feature I can commit to implementing for the foreseeable future, I'm afraid.

You could consider utilising an automation service like Zapier to generate deals when new contacts are sent through, however?
